<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.eclipse.jetty.tck</groupId>
  <artifactId>websocket-tck-run</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <name>websocket-tck-run</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.sources>17</maven.compiler.sources>
    <maven.compiler.release>17</maven.compiler.release>
    <junit.version>5.11.4</junit.version>
    <slf4j.version>2.0.16</slf4j.version>
    <arquillian.core.version>1.9.3.Final</arquillian.core.version>
    <arquillian.jetty.version>2.0.1.Final-SNAPSHOT</arquillian.jetty.version>
    <arquillian.jetty.artifactId>arquillian-jetty-embedded-12-ee11</arquillian.jetty.artifactId>
    <jetty.version>12.1.0.alpha1</jetty.version> <!-- 11.0.9-SNAPSHOT -->
    <surefire.version>3.5.2</surefire.version>
    <fork.argLine>-Xmx8g -Xms4g</fork.argLine>
    <http2.timeout></http2.timeout>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-bom</artifactId>
        <version>${jetty.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty.ee11</groupId>
        <artifactId>jetty-ee11-bom</artifactId>
        <version>${jetty.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>jakarta.tck</groupId>
      <artifactId>websocket-tck-spec-tests</artifactId>
      <version>2.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.container</groupId>
      <artifactId>${arquillian.jetty.artifactId}</artifactId>
      <version>${arquillian.jetty.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-deploy</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-webapp</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-jakarta-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11.websocket</groupId>
      <artifactId>jetty-ee11-websocket-jakarta-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.http2</groupId>
      <artifactId>jetty-http2-server</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-annotations</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-apache-jsp</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jetty.ee11</groupId>
      <artifactId>jetty-ee11-glassfish-jstl</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jul-to-slf4j</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.container</groupId>
      <artifactId>arquillian-container-test-spi</artifactId>
      <version>${arquillian.core.version}</version>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit5</groupId>
      <artifactId>arquillian-junit5-container</artifactId>
      <version>${arquillian.core.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- just make Intellij/jpms happy when having all the projects together -->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-slf4j-impl</artifactId>-->
<!--      <version>${jetty.version}</version>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-jmx</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-util-ajax</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-client</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-webapp</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-xml</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty</groupId>-->
<!--      <artifactId>jetty-util</artifactId>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.eclipse.jetty.tests</groupId>-->
<!--      <artifactId>jetty-http-tools</artifactId>-->
<!--      <version>${jetty.version}</version>-->
<!--      <scope>compile</scope>-->
<!--    </dependency>-->
  </dependencies>

  <build>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.4.1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.14.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire.version}</version>
          <configuration>
            <excludes>
              <exclude>**/AppTest**</exclude>
            </excludes>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.basepom.maven</groupId>
          <artifactId>duplicate-finder-maven-plugin</artifactId>
          <version>2.0.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire.version}</version>
        <executions>
          <execution>
            <phase>verify</phase>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <forkedProcessTimeoutInSeconds>15000</forkedProcessTimeoutInSeconds>
              <dependenciesToScan>
                <dependenciesToScan>jakarta.tck:websocket-tck-spec-tests</dependenciesToScan>
              </dependenciesToScan>
              <systemProperties>
                <http2.timeout>${http2.timeout}</http2.timeout>
                <lib.name>websockettck</lib.name>
                <junit.log.traceflag>true</junit.log.traceflag>
                <ws_wait>5</ws_wait>
                <porting.ts.url.class.1>com.sun.ts.tests.websocket.lib.implementation.sun.common.SunRIURL</porting.ts.url.class.1>
              </systemProperties>
              <trimStackTrace>false</trimStackTrace>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <pluginRepositories>
    <pluginRepository>
      <id>apache.snapshots</id>
      <url>https://repository.apache.org/content/groups/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
  <repositories>
    <repository>
      <id>apache.snapshots</id>
      <url>https://repository.apache.org/content/groups/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>jetty.snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/jetty-snapshots/</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>jetty.staging</id>
      <url>https://oss.sonatype.org/content/groups/jetty-with-staging</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
</project>
