# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Build and run TCK Servlet

on: [push, pull_request]

permissions:
  security-events: read
  contents: write
  actions: read

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout Arquillian
        uses: actions/checkout@v3
        with:
          repository: 'arquillian/arquillian-container-jetty'
          ref: 'jetty-12.0-security-refactoring'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Arquillian with Maven
        run: mvn install -B -U

      - name: Checkout Websocket TCK
        uses: actions/checkout@v3
        with:
          repository: 'olamy/jakartaee-tck'
          ref: 'tck-refactor-websocket-2-arquillian-url'

      - name: Install legacy javatest jar
        run: mvn  -ntp install:install-file -Dfile=./lib/javatest.jar -DgroupId=javatest -DartifactId=javatest -Dversion=5.0 -Dpackaging=jar

      - name: Build Websocket TCK with Maven
        run: mvn -V -B -U -pl :websocket-tck -am clean install -DskipTests -e  -B -U

      - name: Checkout TCK Run
        uses: actions/checkout@v3

      - name: Build TCK Run with Maven
        run: mvn -V -B -U -am clean verify -e  -B -Dmaven.test.failure.ignore=true

